FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY tsconfig.json ./
COPY apps/server ./apps/server
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm run prebuild
RUN pnpm --filter server run build

EXPOSE 3001

CMD ["pnpm", "--filter", "server", "run", "start"]