services:
  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.server
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      NODE_ENV: production

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.web
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: production